name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v5.1.1
          command: idf.py image

      - name: Upload Application Image
        uses: actions/upload-artifact@v3
        with:
          name: Application
          path: build/ipcam.bin

      - name: Upload Filesystem Image
        uses: actions/upload-artifact@v3
        with:
          name: File System
          path: build/fs_0.bin

      - name: Upload Full Flash Image
        uses: actions/upload-artifact@v3
        with:
          name: Full Flash Image
          path: build/ipcam-full.bin
